#include <iostream.h>
#include <conio.h>

int silog, test2, drk,meals,silogs,price;

void main(){
	cout<<"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%";
	cout<<"Welcome To Beth sdhasd restauran";
	cout<<"[1]Silog Meals\n";
	cout<<"[2]Ala carte";
	cout<<"[3]Mainet na Sabaw and Rice Meal\n";
	cout<<"[4]Mikays Combo Meals\n";
	cout<<"Choose Your preffered meals";
	cin>>meals;
switch(meals){
	case 1:
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Choose your preffered silog ";
		cin>>silogs;
			switch(silogs){
				case 1: 
				 price = 100;
				 break;
				 case 2: 
				 price = 120;
				 break;
				 case 3: 
				 price = 100;
				 break;
				 case 4: 
				 price = 120;
				 break;
				 case 5: 
				 price = 100;
				 break;
				 case 6: 
				 price = 120;
				 break;
			
			}
		break;
	case 2:
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Choose your preffered silog ";
		cin>>silogs;
			switch(silogs){
				case 1: 
				 price = 100;
				 break;
				 case 2: 
				 price = 120;
				 break;
				 case 3: 
				 price = 100;
				 break;
				 case 4: 
				 price = 120;
				 break;
				 case 5: 
				 price = 100;
				 break;
				 case 6: 
				 price = 120;
				 break;
			
			}
		break;
	
	

	case 3:
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Choose your preffered silog ";
		cin>>silogs;
			switch(silogs){
				case 1: 
				 price = 100;
				 break;
				 case 2: 
				 price = 120;
				 break;
				 case 3: 
				 price = 100;
				 break;
				 case 4: 
				 price = 120;
				 break;
				 case 5: 
				 price = 100;
				 break;
				 case 6: 
				 price = 120;
				 break;
			
			}
		break;
	
	case 4:
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Choose your preffered silog ";
		cin>>silogs;
			switch(silogs){
				case 1: 
				 price = 100;
				 break;
				 case 2: 
				 price = 120;
				 break;
				 case 3: 
				 price = 100;
				 break;
				 case 4: 
				 price = 120;
				 break;
				 case 5: 
				 price = 100;
				 break;
				 case 6: 
				 price = 120;
				 break;
			
			}
		break;

	case 5:
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Beef Tapsilog";
		cout<<"Choose your preffered silog ";
		cin>>silogs;
			switch(silogs){
				case 1: 
				 price = 100;
				 break;
				 case 2: 
				 price = 120;
				 break;
				 case 3: 
				 price = 100;
				 break;
				 case 4: 
				 price = 120;
				 break;
				 case 5: 
				 price = 100;
				 break;
				 case 6: 
				 price = 120;
				 break;
			
			}
		break;
		
	

	
}



getch();
}